####################################
# Docker-base
#   - To install common requirements
####################################
FROM python:3.6-jessie
LABEL maintainer="Sampath Kumar M"

RUN apt-get update && \
 apt-get install vim -y

RUN apt-get install tesseract-ocr -y

RUN pip install Cython --install-option="--no-cython-compile"
RUN pip install tensorflow

