# Generated by Django 2.1 on 2019-09-09 08:58

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(db_column='image', upload_to=utils.utils.rename_and_upload_path)),
                ('image_name', models.CharField(db_column='image_name', max_length=255)),
            ],
        ),
    ]
